### PR TITLE
Add error message for ifname collision

### PR DESCRIPTION
**Pull request by s1061123**
This changes introduce to validateIfName, to check the validation for interface name, i.e. same name among two or more interfaces.

Before
`Warning  FailedCreatePodSandBox  7s (x3 over 9s)    kubelet, kube-node-2  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "pod-case-01_default" network: netplugin failed but error parsing its diagnostic message "{\n    \"ip4\": {\n        \"ip\": \"10.244.1.14/24\",\n        \"gateway\": \"10.244.1.1\",\n        \"routes\": [\n            {\n                \"dst\": \"10.244.0.0/16\",\n                \"gw\": \"10.244.1.1\"\n            },\n            {\n                \"dst\": \"0.0.0.0/0\",\n                \"gw\": \"10.244.1.1\"\n            }\n        ]\n    },\n    \"dns\": {}\n}{\n    \"code\": 100,\n    \"msg\": \"Multus: error in invoke Delegate add - \\\"macvlan\\\": failed to rename macvlan to \\\"eth0\\\": file exists\"\n}": invalid character '{' after top-level value
`

After
`Warning  FailedCreatePodSandBox  1s    kubelet, kube-node-1  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "pod-case-01_default" network: netplugin failed but error parsing its diagnostic message "{\n    \"ip4\": {\n        \"ip\": \"10.244.3.4/24\",\n        \"gateway\": \"10.244.3.1\",\n        \"routes\": [\n            {\n                \"dst\": \"10.244.0.0/16\",\n                \"gw\": \"10.244.3.1\"\n            },\n            {\n                \"dst\": \"0.0.0.0/0\",\n                \"gw\": \"10.244.3.1\"\n            }\n        ]\n    },\n    \"dns\": {}\n}{\n    \"code\": 100,\n    \"msg\": \"cannot set \\\"macvlan\\\" ifname: ifname eth0 is already exist\"\n}": invalid character '{' after top-level value`

### CODE REVIEW

**Comment by rkamudhan** [comment]
LGTM @s1061123 once we resolve the conflict, we can merge the PR.

**Comment by s1061123** [comment]
@rkamudhan thanks. As far as I look current status, there is no conflict, so I will merge it soon.

**Comment by rkamudhan** [comment]
@s1061123 I saw the rebase showing the conflict.

**Comment by s1061123** [comment]
@rkamudhan got it. I've resolve conflict so wait CI finish then merge.

**Pull request merged**
